### ISSUE TITLE
USB can not update

### ISSUE THREAD

**Issue by onestarshang** [TimonPeng/Proxmark3-use-USB-to-update-the-firmware#1]
your Gravatar scares the hell out of me. (233333

**Comment by TimonPeng** [comment]
![sheldon](https://cloud.githubusercontent.com/assets/8691151/5614491/ccf3547a-952c-11e4-98fb-0545d8fe642c.jpg)

**Comment by onestarshang** [comment]
yep,it is terrible... :-1:

**Comment by onestarshang** [comment]
:smile: love this gravatar~
